[default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = ['lib/=lib']
eth-rpc-url = "https://speedy-nodes-nyc.moralis.io/6968d91b1645c106eef6c4e9/eth/mainnet"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# Below is a Binance Smart Chain Settings

block_number = 17879088
block_timestamp = 1652788378
verbosity = 2
# eth-rpc-url = "https://speedy-nodes-nyc.moralis.io/6968d91b1645c106eef6c4e9/bsc/mainnet"
# eth-rpc-url = "https://speedy-nodes-nyc.moralis.io/6968d91b1645c106eef6c4e9/bsc/mainnet/archive"
# chain_id = 56